config/routes.rb
Rails.application.routes.draw do
  root 'classrooms#index'
  get '/', to: 'classrooms#index'

  get '/search', to: 'application#search'

  resources :students, only: [:index, :show, :new, :create, :update, :destroy]

  get '/teachers/attendances', to: 'teachers#attendances'
  get '/teachers/custom_export', to: 'teachers#teachers_custom_export_form'
  post '/teachers/custom_export', to: 'teachers#teachers_custom_export'
  resources :teachers, only: [:index, :show, :new, :create, :update, :destroy]

  resources :people, only: [:index, :show, :new, :create, :update, :destroy] do
    post '/data_fields/:key', to: 'data_fields#update'
  end

  get '/classrooms/custom_export', to: 'classrooms#classrooms_custom_export_form'
  post '/classrooms/custom_export', to: 'classrooms#classrooms_custom_export'
  resources :classrooms, only: [:index, :show, :new, :create, :update, :destroy] do
    get '/students_personal_details', to: 'classrooms#students_personal_details'
    get '/attendances', to: 'classrooms#attendances'
    get '/evaluations', to: 'classrooms#evaluations'
    get '/custom_export', to: 'classrooms#custom_export_form'
    post '/custom_export', to: 'classrooms#custom_export'
  end

  secondary_resources = [
    :teaching_assignments,
    :enrollments,
    :evaluations,
    :grades,
    :users,
    :attendances,
    :phones,
    :emails,
    :addresses
  ]
  resources :users, only: [:index]

  secondary_resources.each do |resource|
    resources resource, only: [:create, :update, :destroy]
  end

  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  namespace :api do
    # API v1 - JWT authenticated
    namespace :v1 do
      # Authentication
      post '/auth/login', to: 'auth#login'
      post '/auth/logout', to: 'auth#logout'
      post '/auth/refresh', to: 'auth#refresh'
      get '/auth/me', to: 'auth#me'

      # Resource types
      get '/resource_types/:key', to: 'resource_types#index'

      # Main resources (full CRUD)
      resources :classrooms do
        collection do
          get :statistics_pdf
        end
        member do
          get :enrollments
          get :teaching_assignments
          get :attendances
          get :evaluations
        end
      end

      resources :people, only: [:index, :show, :update]
      resources :users, only: [:index, :show, :create, :update, :destroy]
      resources :data_schemas do
        collection do
          get :options
        end
      end

      # Secondary resources
      resources :enrollments
      resources :teaching_assignments
      resources :attendances, only: [:index, :show, :create, :update, :destroy]

      # Search
      get '/search', to: 'search#index'
    end
  end
end

app/models/concerns/person.rb
module Person
  extend ActiveSupport::Concern

  included do
    include VnTextUtils
    validates_presence_of :full_name
    validates :phone, format: { with: /\A\d+\z/, message: 'only allows numbers' }, allow_blank: true
    validates_presence_of(:street_name, if: :street_number?) || :ward? || :district?
  end

  def name
    "#{christian_name} #{full_name}".squish
  end

  def address
    "#{street_number} #{street_name}, #{ward}, #{district}" if street_name?
  end

  def sort_param
    normalize(reverse(name))
  end
end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id             :integer          not null, primary key
#  avatar_url     :string
#  birth_date     :date
#  birth_place    :string
#  christian_name :string
#  data           :jsonb
#  deleted_at     :datetime
#  gender         :string           not null
#  name           :string           not null
#  nickname       :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class Person < ApplicationRecord
  include VnTextUtils
  include DataFieldable

  def self.ransackable_attributes(auth_object = nil)
    %w[christian_name name gender birth_date birth_place nickname created_at updated_at]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[enrollments teaching_assignments]
  end

  has_one :user
  has_one :teacher
  has_one :student
  has_many :phones, as: :phoneable
  has_many :emails, as: :emailable
  has_many :addresses, as: :addressable

  has_many :enrollments
  # has_many :classrooms, through: :enrollments

  has_many :teaching_assignments
  # has_many :classrooms, through: :teaching_assignments

  validates_presence_of :name, :gender, :birth_date
  validates :gender, inclusion: { in: %w[Nam Nữ], message: 'have to be either Nam or Nữ' }

  scope :in_classroom, -> (classroom) { joins(:enrollments).where('enrollments.classroom_id': classroom.id) }

  FIELD_SETS = [
    {
      key: 'person',
      fields: [
        { field_name: :christian_name, label: 'Tên Thánh' },
        { field_name: :name, label: 'Họ và Tên' },
        { field_name: :gender, label: 'Giới Tính', field_type: :select },
        { field_name: :nickname, label: 'Tên Ngắn', display_permission: -> (user) { user.admin? } },
        { field_name: :birth_date, label: 'Ngày Sinh', field_type: :date_field },
        { field_name: :birth_place, label: 'Nơi Sinh' },
        { field_name: :avatar_url, label: 'Ảnh Đại Diện' },
      ]
    }
  ]

  def full_name
    "#{christian_name} #{name}".squish
  end

  def primary_phone
    phones.where(primary: true).take&.number
  end

  def primary_email
    emails.where(primary: true).take&.address
  end

  def sort_param
    normalize(reverse(name))
  end
end

app/controllers/api/v1/people_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class PeopleController < BaseController
      before_action :set_person, only: [:show, :update]

      # GET /api/v1/people
      def index
        @people = scope.result.page(params[:page]).per(params[:per_page] || 50)
        render_collection @people, meta: pagination_meta(@people)
      end

      # GET /api/v1/people/:id
      def show
        render_resource @person
      end

      # PATCH/PUT /api/v1/people/:id
      def update
        authorize @person

        if @person.update(person_params)
          render_resource @person
        else
          render json: { errors: @person.errors.full_messages }, status: :unprocessable_entity
        end
      end

      private

      def scope
        base = Person.all

        # Filter by role: student (has enrollments) or teacher (has teaching_assignments)
        case params[:role]
        when 'student'
          base = base.joins(:enrollments).distinct
          base = base.joins('INNER JOIN classrooms ON classrooms.id = enrollments.classroom_id')
                     .where(classrooms: { year: params[:year] }) if params[:year].present?
        when 'teacher'
          base = base.joins(:teaching_assignments).distinct
          base = base.joins('INNER JOIN classrooms ON classrooms.id = teaching_assignments.classroom_id')
                     .where(classrooms: { year: params[:year] }) if params[:year].present?
        end

        base.ransack(params[:filters])
      end

      def set_person
        @person = Person.find(params[:id])
      end

      def person_params
        params.require(:person).permit(
          :first_name, :middle_name, :last_name, :full_name,
          :christian_name, :date_of_birth, :sex, :avatar_url
        )
      end
    end
  end
end

app/controllers/people_controller.rb
# == Schema Information
#
# Table name: people
#
#  id             :integer          not null, primary key
#  avatar_url     :string
#  birth_date     :date
#  birth_place    :string
#  christian_name :string
#  data           :jsonb
#  deleted_at     :datetime
#  gender         :string           not null
#  name           :string           not null
#  nickname       :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class PeopleController < ApplicationController
  before_action :set_person, except: %i[index create]

  def index

  end

  def show

  end

  def create

  end

  def update
    flash[:success] = 'Person was successfully updated.' if @person.update(person_params)
    redirect_back(fallback_location: root_path)
  end

  private

  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(
      :christian_name,
      :name,
      :nickname,
      :birth_date,
      :birth_place,
      :gender,
      :avatar_url
    )
  end
end

app/views/people/index.html.erb
 <h1>Danh Sách Người Dùng</h1>

app/views/people/show.html.erb
<%
  heading = @person.full_name
  student = @person.student
  teacher = @person.teacher
  user = @person.user
  user ||= User.new(teacher: teacher, person: @person) if @current_user.admin?
  editable = @current_user.admin?
%>

<h1><%= heading %></h1>
<%= render 'components/form/form',
           heading: 'Thông Tin Cá Nhân',
           object: @person,
           editable: editable
%>
<%= render 'components/form/form',
           heading: 'Số Điện Thoại',
           object: @person.phones.first_or_initialize(primary: true),
           editable: editable
%>
<%= render 'components/form/form',
           heading: 'Email',
           object: @person.emails.first_or_initialize(primary: true),
           editable: editable
%>
<%= render 'components/form/form',
           heading: 'Địa Chỉ Nhà',
           object: @person.addresses.first_or_initialize(primary: true),
           editable: editable
%>

<%= render 'components/form/data_fields',
           object: @person,
           schema_key: 'sacraments',
           editable: editable
%>

<%= render 'components/form/data_fields',
           object: @person,
           schema_key: 'parents_info',
           editable: editable
%>

<%= render 'components/form/data_fields',
           object: @person,
           schema_key: 'additional_info',
           editable: editable
%>

<%= render 'enrollments/index', enrollments: student.enrollments if student %>
<%= render 'teaching_assignments/index', teaching_assignments: teacher.teaching_assignments, teacher: teacher %>

<%= render 'components/form/form',
           heading: 'Thông tin đăng nhập',
           object: user,
           editable: user && @current_user.admin_or_self_teacher?(teacher) if teacher
%>

<%= render 'components/button_group', heading: 'In Ấn', actions: [{ label: 'In Sơ Yếu Lý Lịch', path: student_path(format: "pdf") }] if student %>
<% if @current_user.admin? && @current_user.person == @person %>
  <%= render 'components/button_group', heading: 'Chức năng Admin', actions: [
    { label: 'Tạo Lớp Học', path: new_classroom_path },
    { label: 'Tạo Thiếu Nhi', path: new_student_path },
    { label: 'Tạo Giáo Lý Viên', path: new_teacher_path },
  ] %>
<% end %>