config/routes.rb
Rails.application.routes.draw do
  root 'classrooms#index'
  get '/', to: 'classrooms#index'

  get '/search', to: 'application#search'

  resources :students, only: [:index, :show, :new, :create, :update, :destroy]

  get '/teachers/attendances', to: 'teachers#attendances'
  get '/teachers/custom_export', to: 'teachers#teachers_custom_export_form'
  post '/teachers/custom_export', to: 'teachers#teachers_custom_export'
  resources :teachers, only: [:index, :show, :new, :create, :update, :destroy]

  resources :people, only: [:index, :show, :new, :create, :update, :destroy] do
    post '/data_fields/:key', to: 'data_fields#update'
  end

  get '/classrooms/custom_export', to: 'classrooms#classrooms_custom_export_form'
  post '/classrooms/custom_export', to: 'classrooms#classrooms_custom_export'
  resources :classrooms, only: [:index, :show, :new, :create, :update, :destroy] do
    get '/students_personal_details', to: 'classrooms#students_personal_details'
    get '/attendances', to: 'classrooms#attendances'
    get '/evaluations', to: 'classrooms#evaluations'
    get '/custom_export', to: 'classrooms#custom_export_form'
    post '/custom_export', to: 'classrooms#custom_export'
  end

  secondary_resources = [
    :teaching_assignments,
    :enrollments,
    :evaluations,
    :grades,
    :users,
    :attendances,
    :phones,
    :emails,
    :addresses
  ]
  resources :users, only: [:index]

  secondary_resources.each do |resource|
    resources resource, only: [:create, :update, :destroy]
  end

  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  namespace :api do
    # API v1 - JWT authenticated
    namespace :v1 do
      # Authentication
      post '/auth/login', to: 'auth#login'
      post '/auth/logout', to: 'auth#logout'
      post '/auth/refresh', to: 'auth#refresh'
      get '/auth/me', to: 'auth#me'

      # Resource types
      get '/resource_types/:key', to: 'resource_types#index'

      # Main resources (full CRUD)
      resources :classrooms do
        collection do
          get :statistics_pdf
        end
        member do
          get :enrollments
          get :teaching_assignments
          get :attendances
          get :evaluations
        end
      end

      resources :people, only: [:index, :show, :update]
      resources :users, only: [:index, :show, :create, :update, :destroy]
      resources :data_schemas do
        collection do
          get :options
        end
      end

      # Secondary resources
      resources :enrollments
      resources :teaching_assignments
      resources :attendances, only: [:index, :show, :create, :update, :destroy]

      # Search
      get '/search', to: 'search#index'
    end
  end
end

app/models/teacher.rb
# == Schema Information
#
# Table name: teachers
#
#  id             :integer          not null, primary key
#  christian_name :string
#  date_birth     :date
#  deleted_at     :datetime
#  district       :string
#  email          :string
#  full_name      :string
#  gender         :string
#  named_date     :string
#  nickname       :string
#  occupation     :string
#  phone          :string
#  street_name    :string
#  street_number  :string
#  ward           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  person_id      :integer
#
# Indexes
#
#  index_teachers_on_deleted_at  (deleted_at)
#
class Teacher < ApplicationRecord
  include PersonConcern

  has_one :user
  has_many :teaching_assignments
  has_many :classrooms, through: :teaching_assignments
  belongs_to :person
  # TODO: email = right format, allow nil

  before_validation :sync_person

  FIELD_SETS = [
    {
      key: 'teacher',
      fields: [
        { field_name: :christian_name, label: 'Tên Thánh' },
        { field_name: :full_name, label: 'Họ và Tên' },
        { field_name: :gender, label: 'Giới Tính', field_type: :select },
        { field_name: :nickname, label: 'Tên Ngắn', display_permission: -> (user) { user.admin? } },
        { field_name: :date_birth, label: 'Ngày Sinh', field_type: :date_field },
        { field_name: :named_date, label: 'Bổn Mạng' },
        { field_name: :phone, label: 'Số Điện Thoại' },
        { field_name: :email, label: 'Email' },
        { field_name: :street_number, label: 'Số Nhà' },
        { field_name: :street_name, label: 'Đường' },
        { field_name: :ward, label: 'Phường/Xã' },
        { field_name: :district, label: 'Quận/Huyện' }
      ]
    }
  ]

  def sync_person
    person = person_id ? Person.find(person_id) : Person.new
    person.christian_name = christian_name
    person.name = full_name
    person.nickname = nickname
    person.gender = gender
    person.birth_date = date_birth
    person.data = {
      'additional_info' => {
        'named_date' => named_date,
        'occupation' => occupation
      }
    }
    person.save

    person.phones.where(primary: true).first_or_create.update(number: phone) if phone
    person.emails.where(primary: true).first_or_create.update(address: email) if email
    person.addresses.where(primary: true).first_or_initialize.update(
      street_number: street_number,
      street_name: street_name,
      ward: ward,
      district: district
    ) if street_name

    self.person_id = person.id unless person_id
  end
end

app/controllers/teachers_controller.rb
# == Schema Information
#
# Table name: teachers
#
#  id             :integer          not null, primary key
#  christian_name :string
#  date_birth     :date
#  deleted_at     :datetime
#  district       :string
#  email          :string
#  full_name      :string
#  gender         :string
#  named_date     :string
#  nickname       :string
#  occupation     :string
#  phone          :string
#  street_name    :string
#  street_number  :string
#  ward           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  person_id      :integer
#
# Indexes
#
#  index_teachers_on_deleted_at  (deleted_at)
#
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[show update destroy admin_or_self?]

  # GET /teachers
  # GET /teachers.json
  def index
    authorize Teacher
    @teaching_assignments = TeachingAssignment.joins(:classroom).where('classrooms.year = ?', @current_year).sort_by(&:sort_param)
    respond_to do |format|
      format.html
      format.pdf do
        pdf = TeachersPdf.new(@teaching_assignments, @current_year)
        send_data pdf.render,
                  filename: "Danh Sách GLV Năm Học #{@current_year_long}.pdf",
                  type: 'application/pdf',
                  disposition: 'inline'
      end
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    authorize @teacher
  end

  # GET /teachers/new
  def new
    authorize Teacher

    @teacher = Teacher.new
    render :show
  end

  # POST /teachers
  # POST /teachers.json
  def create
    authorize Teacher

    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        flash[:success] = 'Teacher was successfully created.'
        format.html { redirect_to @teacher }
      else
        format.html { render :show }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    authorize @teacher

    respond_to do |format|
      if @teacher.update(teacher_params)
        flash[:success] = 'Teacher was successfully updated.'
        format.html { redirect_to @teacher }
      else
        format.html { render :show }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    authorize @teacher

    @teacher.teaching_assignments.each(&:destroy)

    @teacher.destroy
    respond_to do |format|
      flash[:success] = 'Teacher was successfully destroyed.'
      format.html { redirect_to teachers_url }
    end
  end

  def teachers_custom_export_form
    authorize Teacher, :index?

    render 'custom_export/form', locals: { title: 'Giáo Lý Viên', path: teachers_custom_export_path }
  end

  def teachers_custom_export
    authorize Teacher, :index?

    @teaching_assignments = TeachingAssignment.for_year(@current_year).sort_by(&:sort_param)

    pdf = TeachersCustomPdf.new(@teaching_assignments, params[:title], params[:page_layout].to_sym, params[:columns].split(','))
    send_data pdf.render, filename: "#{params[:title]}.pdf", type: 'application/pdf', disposition: 'inline'
  end

  def attendances
    authorize TeachingAssignment, :update?
  end

private

  # Use callbacks to share common setup or constraints between actions.
  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def teacher_params
    params.require(:teacher).permit(
      :christian_name,
      :full_name,
      :nickname,
      :date_birth,
      :gender,
      :phone,
      :email,
      :street_number,
      :street_name,
      :ward,
      :district,
      :named_date,
      :occupation
    )
  end
end

app/views/teachers/_info_table.html.erb
<%= render 'components/collapsible', heading: 'Giáo Lý Viên' do %>
  <% teaching_assignments ||= [] %>
  <h4>Số Lượng : <%= teaching_assignments.count %></h4>
  <table>
    <thead>
      <tr>
        <th style='width:  30px'>STT</th>
        <th style='width:  80px'>Lớp</th>
        <th style='width:  90px'>Phụ Trách</th>
        <th style='width: 280px'>Tên Thánh - Họ và Tên</th>
        <th style='width:  80px'>Ngày Sinh</th>
        <th style='width: 120px'>Bổn Mạng</th>
        <th style='width: 220px'>Địa Chỉ</th>
        <th style='width:  90px'>Điện Thoại</th>
      </tr>
    </thead>

    <tbody>
    <% teaching_assignments.each_with_index do |teaching_assignment, index| %>
      <% classroom = teaching_assignment.classroom %>
      <% teacher = teaching_assignment.teacher %>

      <tr class="table-row">
        <td style='width:  30px'><%= index+1 %></td>
        <td style='width:  80px'><%= classroom ? (link_to classroom.name, classroom) : '' %></td>
        <td style='width:  80px'><%= teaching_assignment.position %></td>
        <td style='width: 280px'><%= link_to teacher.name, teacher %></td>
        <td style='width: 100px'><%= teacher.date_birth&.strftime("%d-%m-%Y") %></td>
        <td style='width: 110px'><%= teacher.named_date %></td>
        <td style='width: 220px'><%= teacher.address %></td>
        <td style='width:  90px'><%= teacher.phone %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/teachers/_teacher_guidances.html.erb
<% classrooms = @teacher&.classrooms || [] %>
<% years = Classroom.uniq.order(year: :desc).pluck(:year) %>
<% opts = Classroom.where(year: years[0]).sort_by(&:sort_param).map { |c| [c.name, c.id] } %>

<h1>Hành Trình Thiêng Liêng</h1>

<table>
  <thead>
  <tr>
    <th style='width: 100px'>Năm Học</th>
    <th style='width: 100px'>Tên Lớp</th>
    <th style='width: 100px'>Phụ Trách</th>
    <th style='width: 200px'>Vị Trí</th>
  </tr>
  </thead>

  <tbody>
  <% classrooms.each do |classroom| %>
    <% guidance = @teacher.guidances.select { |guidance| guidance.classroom_id == classroom.id }.first %>
    <% default_location = "Vô Gia Cư"; default_location = classroom.location if classroom.location? %>
    <% default_position = "---"; default_position = guidance.position if guidance.position? %>
    <tr class="table-row">
      <td style='width: 200px'><%= classroom.long_year %></td>
      <td style='width: 200px'><%= link_to classroom.name, classroom %></td>
      <td style='width: 200px'><%= link_to default_position, edit_guidance_path(guidance.id) %></td>
      <td style='width: 200px'><%= default_location %></td>
    </tr>
  <% end %>

  <tr class="table-row">
    <td id="form" style="font-size: 14px; display: none" colspan="4">
      <% @guidance = Guidance.new %>
      <%= form_for(@guidance) do |f| %>
        <% if @guidance.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@guidance.errors.count, "error") %> prohibited this guidance from being saved:</h2>

            <ul>
              <% @guidance.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.hidden_field :teacher_id, :value => @teacher.id %>
        <select id="year_combobox" onchange="changeClassroom()">
          <% years.each do |year| %>
            <option value="<%=year%>"><%= year.to_s + " - " + (year.to_i+1).to_s %></option>
          <% end %>
        </select>
        <%= f.select :classroom_id, options_for_select(opts), :id => 'classroom_id' %>
        <%= f.select :position, options_for_select(["Tu Sĩ", "Huynh Trưởng", "Dự Trưởng", "Hiệp Sĩ", "GLV", "Tiền GLV", "Phụ Tá", "Kiến Tập"]), :style => "width: 98px"%>
        <%= f.submit "Thêm Lớp Mới" %>
      <% end %>
    </td>
  </tr>
  </tbody>
</table>

<% if @current_user&.admin? %>
  <button id="btn" onClick="showForm()" class="button">Thêm Lớp Mới</button>
<% end %>

<script>
  function showForm() {
    document.getElementById("btn").style.display = "none";
    document.getElementById("form").style.display = "table-cell";
  }

  function changeClassroom() {
    const e = document.getElementById("year_combobox");
    const selected = e.options[e.selectedIndex].value;

    //Create array of options to be added
    const hash = {};
    const keys = [];

    <% Classroom.all.sort_by(&:sort_param).each do |classroom| %>
    if(selected === "<%= classroom.year %>") {
      hash[<%= classroom.id %>] = "<%= classroom.name %>";
      keys.push(<%= classroom.id %>);
    }
    <% end %>

    const list = document.getElementById("guidance_classroom_id");
    list.options.length = 0;

    //Create and append the options
    for (let i = 0; i < keys.length; i++) {
      const option = document.createElement("option");
      option.value = keys[i];
      option.text = hash[keys[i]];
      list.appendChild(option);
    }

  }
</script>

app/views/teachers/attendances.html.erb
<%
  date = params[:date]&.to_date || Date.today
  sundays = (@current_year_start_date.to_date..@current_year_end_date.to_date).to_a.select {|k| k.wday == 0}
  actions = sundays.map do |sunday|
    { label: sunday.strftime('%d-%m-%Y'), path: 'attendances', params: {date: sunday} }
  end
%>

<h1>Điểm danh Giáo Lý Viên</h1>
<%= render 'components/button_group', heading: 'Ngày Điểm Danh', actions: actions %>
<% if sundays.include?(date) %>
  <%= render 'components/collapsible', heading: "Điểm danh Giáo Lý Viên - Ngày #{date.strftime('%d-%m-%Y')}", always_open:true do %>
    <table>
      <thead>
        <tr>
          <th>Lớp</th>
          <th>Phụ Trách</th>
          <th>Giáo Lý Viên</th>
          <th><%= date.strftime('%d-%m-%Y') %></th>
          <th>Ngày Báo</th>
          <th>Lý Do</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% teaching_assignments = TeachingAssignment.for_year(@current_year).sort_by { |g| g.sort_param } %>
        <% attendances = Attendance.where(attendable: teaching_assignments, date: date) %>
        <% teaching_assignments.each do |teaching_assignment| %>
          <tr>
            <% attendance = attendances.find { |attendance| attendance.attendable == teaching_assignment } || Attendance.new(attendable: teaching_assignment, date: date) %>
            <td><%= teaching_assignment.classroom.name %></td>
            <td><%= teaching_assignment.position %></td>
            <td><%= teaching_assignment.teacher.name %></td>
            <td>
              <%= render 'components/form/inline_select', object: attendance, field: :status, enabled: @current_user.admin? %>
            </td>
            <%= form_for attendance do |f| %>
              <%= f.hidden_field :id %>
              <%= f.hidden_field :attendable_id %>
              <%= f.hidden_field :attendable_type %>
              <%= f.hidden_field :date %>
              <%= f.hidden_field :status %>
              <td><%= f.date_field :notice_date %></td>
              <td><%= f.text_field :note %></td>
              <td><button>Cập Nhật</button></td>
            <% end %>

          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
<% end %>

app/views/teachers/index.html.erb
<%
  actions = [
    { label: 'In Danh Sách GLV', path: teachers_path(format: :pdf) },
    { label: 'In Bảng Tự Tạo', path: teachers_custom_export_path },
    { label: 'Điểm Danh', path: 'teachers/attendances' }
  ]
%>

<%= render 'info_table', teaching_assignments: @teaching_assignments %>
<%= render 'components/button_group', heading: 'In Ấn', actions: actions %>

app/views/teachers/show.html.erb
<%
  heading = @teacher.id ? @teacher.name : 'Tạo Giáo Lý Viên'
  admin_actions = [
    { label: 'Tạo Lớp Học', path: new_classroom_path },
    { label: 'Tạo Thiếu Nhi', path: new_student_path },
    { label: 'Tạo Giáo Lý Viên', path: new_teacher_path },
  ]
%>

<h1><%= heading %></h1>
<%= render 'components/form/form',
           heading: 'Thông Tin Giáo Lý Viên',
           object: @teacher,
           editable: @current_user.admin_or_self_teacher?(@teacher)
%>
<%= render 'teaching_assignments/index', teaching_assignments: @teacher.teaching_assignments, teacher: @teacher %>
<% user = @teacher.user %>
<% user = User.new(teacher: @teacher) if !user && @current_user.admin? %>
<%= render 'components/form/form',
           heading: 'Thông tin đăng nhập',
           object: user,
           editable: @current_user.admin_or_self_teacher?(@teacher) if user
%>

<% if @current_user.admin? && @current_user.self_teacher?(@teacher) %>
  <%= render 'components/button_group', heading: 'Chức năng Admin', actions: admin_actions %>
<% end %>

<% if @current_user.username == 'ldt' && @teacher.person&.id %>
  <%= render 'components/button_group', heading: 'Person', actions: [{ label: 'Person', path: person_path(@teacher.person) }] %>
<% end %>