config/routes.rb
Rails.application.routes.draw do
  root 'classrooms#index'
  get '/', to: 'classrooms#index'

  get '/search', to: 'application#search'

  resources :students, only: [:index, :show, :new, :create, :update, :destroy]

  get '/teachers/attendances', to: 'teachers#attendances'
  get '/teachers/custom_export', to: 'teachers#teachers_custom_export_form'
  post '/teachers/custom_export', to: 'teachers#teachers_custom_export'
  resources :teachers, only: [:index, :show, :new, :create, :update, :destroy]

  resources :people, only: [:index, :show, :new, :create, :update, :destroy] do
    post '/data_fields/:key', to: 'data_fields#update'
  end

  get '/classrooms/custom_export', to: 'classrooms#classrooms_custom_export_form'
  post '/classrooms/custom_export', to: 'classrooms#classrooms_custom_export'
  resources :classrooms, only: [:index, :show, :new, :create, :update, :destroy] do
    get '/students_personal_details', to: 'classrooms#students_personal_details'
    get '/attendances', to: 'classrooms#attendances'
    get '/evaluations', to: 'classrooms#evaluations'
    get '/custom_export', to: 'classrooms#custom_export_form'
    post '/custom_export', to: 'classrooms#custom_export'
  end

  secondary_resources = [
    :teaching_assignments,
    :enrollments,
    :evaluations,
    :grades,
    :users,
    :attendances,
    :phones,
    :emails,
    :addresses
  ]
  resources :users, only: [:index]

  secondary_resources.each do |resource|
    resources resource, only: [:create, :update, :destroy]
  end

  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  namespace :api do
    # API v1 - JWT authenticated
    namespace :v1 do
      # Authentication
      post '/auth/login', to: 'auth#login'
      post '/auth/logout', to: 'auth#logout'
      post '/auth/refresh', to: 'auth#refresh'
      get '/auth/me', to: 'auth#me'

      # Resource types
      get '/resource_types/:key', to: 'resource_types#index'

      # Main resources (full CRUD)
      resources :classrooms do
        collection do
          get :statistics_pdf
        end
        member do
          get :enrollments
          get :teaching_assignments
          get :attendances
          get :evaluations
        end
      end

      resources :people, only: [:index, :show, :update]
      resources :users, only: [:index, :show, :create, :update, :destroy]
      resources :data_schemas do
        collection do
          get :options
        end
      end

      # Secondary resources
      resources :enrollments
      resources :teaching_assignments
      resources :attendances, only: [:index, :show, :create, :update, :destroy]

      # Search
      get '/search', to: 'search#index'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  before_action :set_current_year, :set_current_user, :auth, :set_paper_trail_whodunnit
  # after_action :verify_authorized

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  attr_reader :current_user

  def search
    @students = params[:query] ? Student.where('full_name ILIKE ?', "%#{params[:query]}%") : []
    @enrollments = @students&.map { |s| s.enrollments.for_year(@current_year).first || s.enrollments.new(result: '') }.compact

    @teachers = params[:query] ? Teacher.where('full_name ILIKE ?', "%#{params[:query]}%") : []
    @teaching_assignments = @teachers&.map { |t| t.teaching_assignments.for_year(@current_year).first || t.teaching_assignments.new(position: '') }.compact
  end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
  def set_current_year
    @current_year = params[:year]&.to_i || 2025
    @current_year_long = "#{@current_year} - #{@current_year + 1}"
    @current_year_start_date = '2025.09.07'
    @current_year_end_date = '2026.05.31'
  end

  def set_current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end

  def auth
    redirect_to login_path unless current_user
  end

  def user_not_authorized
    flash[:warning] = "You are not authorized to perform this action."
    redirect_back(fallback_location: root_path)
  end

  def set_paper_trail_whodunnit
    PaperTrail.request.whodunnit = current_user&.id
  end
end

app/views/application/new.html.erb
<%= link_to "NEW CELL", new_cell_path, :class => "button" %>
<%= link_to "NEW STUDENT", new_student_path, :class => "button" %>
<%= link_to "NEW TEACHER", new_teacher_path, :class => "button" %>

app/views/application/search.html.erb
<%= render 'students/info_table', enrollments: @enrollments unless @enrollments.empty? %>
<%= render 'teachers/info_table', teaching_assignments: @teaching_assignments unless @teaching_assignments.empty? %>

app/views/application/searchByName.html.erb
<h1>SEARCH</h1>


<h2>Search for Student</h2>
<form action="/search" method="get">
    <div style="text-align: center;">
        <div class="block">
            <div class="label">Name:</div>
            <input type="text" name="student_name"/>
        </div>
    </div>
    <div class="actions" style="padding-top:10px">
      <input type="submit" class="button" value="Search"/>
    </div>
</form>

<h2>Search for Teacher</h2>
<form action="/search" method="get">
    <div style="text-align: center;">
        <div class="block">
            <div class="label">Name:</div>
          <input type="text" name="teacher_name"/>
        </div>
    </div>
    <div class="actions" style="padding-top:10px">
      <input type="submit" class="button" value="Search"/>
    </div>
</form>


<% unless @students.nil? %>
    <h2>Count : <%= @students.count %></h2>
    <% @students.each do |s| %>
    <%= link_to s.full_name, s %>
    <br>
    <% end %>
<% end %>

<% unless @teachers.nil? %>
    <h2>Count : <%= @teachers.count %></h2>
    <% @teachers.each do |t| %>
    <%= link_to t.full_name, t %>
    <br>
    <% end %>
<% end %>